/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import control.Config;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.UIManager;
/**
 *
 * @author Renzo
 */
public class Ventana extends javax.swing.JFrame {
    Programa prg;
    
    static Ventana vnt;
    static Control app;
    static Config cfg;
    boolean ready = false;
    
    public Ventana() {
        initComponents();
        
        java.awt.EventQueue.invokeLater(() -> {
            cfg = Config.instance();
            app = new Control(vnt);
            app.iniciar();
            ready = true;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        panelSoporte = new JPanel();
        mensaje = new JTextField();
        enviar = new JButton();
        jScrollPane1 = new JScrollPane();
        mensajes = new JTextPane();
        btnApagar = new JButton();
        btnSoporte = new JButton();
        btnEncender = new JButton();
        jMenuItem3 = new JMenuItem();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soporte URP");
        setResizable(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                formWindowClosing(e);
            }
        });
        Container contentPane = getContentPane();

        //======== panelSoporte ========
        {
            panelSoporte.setAlignmentX(0.0F);

            // JFormDesigner evaluation mark
            panelSoporte.setBorder(new javax.swing.border.CompoundBorder(
                new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0),
                    "JFormDesigner Evaluation", javax.swing.border.TitledBorder.CENTER,
                    javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    java.awt.Color.red), panelSoporte.getBorder())); panelSoporte.addPropertyChangeListener(new java.beans.PropertyChangeListener(){public void propertyChange(java.beans.PropertyChangeEvent e){if("border".equals(e.getPropertyName()))throw new RuntimeException();}});


            //---- mensaje ----
            mensaje.setText("Escriba su mensaje");

            //---- enviar ----
            enviar.setText("Enviar");
            enviar.addActionListener(e -> enviarActionPerformed(e));

            //======== jScrollPane1 ========
            {

                //---- mensajes ----
                mensajes.setEditable(false);
                mensajes.setContentType("text/html");
                jScrollPane1.setViewportView(mensajes);
            }

            GroupLayout panelSoporteLayout = new GroupLayout(panelSoporte);
            panelSoporte.setLayout(panelSoporteLayout);
            panelSoporteLayout.setHorizontalGroup(
                panelSoporteLayout.createParallelGroup()
                    .addGroup(panelSoporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSoporteLayout.createParallelGroup()
                            .addComponent(jScrollPane1)
                            .addGroup(panelSoporteLayout.createSequentialGroup()
                                .addComponent(mensaje, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enviar, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
            );
            panelSoporteLayout.setVerticalGroup(
                panelSoporteLayout.createParallelGroup()
                    .addGroup(panelSoporteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSoporteLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(mensaje, GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(enviar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
            );
        }

        //---- btnApagar ----
        btnApagar.setIcon(new ImageIcon(getClass().getResource("/imagenes/apagarpc.png")));
        btnApagar.setBorder(null);
        btnApagar.setContentAreaFilled(false);
        btnApagar.setEnabled(false);
        btnApagar.addActionListener(e -> btnApagarActionPerformed(e));

        //---- btnSoporte ----
        btnSoporte.setIcon(new ImageIcon(getClass().getResource("/imagenes/soporte.png")));
        btnSoporte.setBorder(null);
        btnSoporte.setContentAreaFilled(false);
        btnSoporte.setEnabled(false);
        btnSoporte.addActionListener(e -> btnSoporteActionPerformed(e));

        //---- btnEncender ----
        btnEncender.setIcon(new ImageIcon(getClass().getResource("/imagenes/encender.png")));
        btnEncender.setText("Hola");
        btnEncender.setToolTipText("");
        btnEncender.setBorder(null);
        btnEncender.setContentAreaFilled(false);
        btnEncender.setEnabled(false);
        btnEncender.addActionListener(e -> btnEncenderActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(btnApagar)
                        .addComponent(btnSoporte)
                        .addComponent(btnEncender))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(panelSoporte, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(panelSoporte, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnEncender, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSoporte, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnApagar, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);

        //---- jMenuItem3 ----
        jMenuItem3.setText("jMenuItem3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        if( !ready ){
            System.out.println("Esta cargando");
            return;
        }
        
        app.btnProyector();
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoporteActionPerformed
        app.btnSoporte();
        
        if( this.getSize().width==350 ){
            this.setSize(950, this.getSize().height);
            this.repaint();
        } else {
            this.setSize(350, this.getSize().height);
        }
    }//GEN-LAST:event_btnSoporteActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if( !ready ){
            System.out.println("Esta cargando");
            return;
        }
        
        app.btnApagar();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vnt.setExtendedState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_formWindowClosing

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        app.btnEnviar();
    }//GEN-LAST:event_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {}

        java.awt.EventQueue.invokeLater(() -> {
            vnt = new Ventana();
            
            vnt.setIconImage( Toolkit.getDefaultToolkit().getImage( vnt.getClass().getResource("/imagenes/urp.png") ) );
            vnt.getContentPane().setBackground(Color.WHITE);
            vnt.repaint();
            vnt.setSize(350, vnt.getSize().height);
            vnt.setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JPanel panelSoporte;
    public JTextField mensaje;
    public JButton enviar;
    private JScrollPane jScrollPane1;
    public JTextPane mensajes;
    public JButton btnApagar;
    public JButton btnSoporte;
    public JButton btnEncender;
    private JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
